### ISSUE TITLE
Error during startup in make-svg-sprite

### ISSUE THREAD

**Issue by d-2rational** [apostrophecms/starter-kit-ecommerce#20]
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

1. Create a new Apostrophe project using the eCommerce starter kit 
2. Start the new project with `npm run dev`

## Expected behavior
Normal startup in local environment. 

## Describe the bug
Receive an error message related to `make-svg-sprite` and project fails to start

## Details
Error message: 

```
C:\Users\...\Documents\Web\ecomm-test>npm run dev

> ecomm-test@1.0.0 dev
> npm run build:sprite && nodemon


> ecomm-test@1.0.0 build:sprite
> ./scripts/make-svg-sprite

'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Version of Node.js:**
Node v18.16.0

**Server Operating System:**
Windows 10 (no Docker)

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Comment by BoDonkey** [comment]
Thanks for bringing this to our attention. We would ask that you try to recreate the error while running WSL as recommended in our [documentation](https://v3.docs.apostrophecms.org/guide/setting-up.html#setting-up). This should make this error go away.

**Comment by d-2rational** [comment]
Running in WSL resolved this issue. Thanks!
